# Runner information:
# ACCA-Beast (12 cpus, 32 GiB memory)
# NVIDIA GeForce GTX 960, Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz

name: CI-gpu

#on:
  ## Trigger the workflow on push or pull request,
  ## but only for the master branch
  #push:
    #branches:
      #- master
  #pull_request:
    #branches:
      #- master
on: push

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.tags }}

    env:
      #DEVITO_ARCH: ${{ matrix.arch }}
      #DEVITO_PLATFORM: ${{ matrix.platform }}
      #DEVITO_LANGUAGE: ${{ matrix.language }}
      OMPI_CC: ${{ matrix.arch }}

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        name: [
          pytest-gpu-omp
          #pytest-gpu-omp,
          #pytest-gpu-acc
        ]
        include:
        - name: pytest-gpu-omp
          test_file: "tests/test_gpu_openmp.py"
          arch: "clang"
          platform: "nvidiaX"
          language: "openmp"
          tags: ["self-hosted", "rhodrin"]

        #- name: pytest-gpu-acc
          #test_file: "tests/test_gpu_openacc.py"
          #arch: "pgcc"
          #platform: "nvidiaX"
          #language: "openacc"
          #tags: ["self-hosted", "gpu", "openacc"]

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        source ~/environments/openmp/bin/activate
        source  ~/environments/scripts/openmp_env.sh
        pip3 install --upgrade pip
        pip3 install -e .[extras]

    - name: Test with pytest
      run: |
        #if [ "${{ matrix.name }}" == 'pytest-gpu-acc' ]; then
          #pgaccelinfo
        #fi
        source ~/environments/openmp/bin/activate
        source  ~/environments/scripts/openmp_env.sh
        pytest --cov --cov-config=.coveragerc --cov-report=xml ${{ matrix.test_file }}

    - name: Test examples
      run: |
        source ~/environments/openmp/bin/activate
        source  ~/environments/scripts/openmp_env.sh
        pytest examples/seismic/acoustic/acoustic_example.py
        pytest examples/seismic/elastic/elastic_example.py
        pytest examples/seismic/tti/tti_example.py
        pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        pytest examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Test examples with MPI
      run: |
        source ~/environments/openmp/bin/activate
        source  ~/environments/scripts/openmp_env.sh
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/tti/tti_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py

    #- name: Upload coverage to Codecov
      #uses: codecov/codecov-action@v1.0.6
      #with:
        #token: ${{ secrets.CODECOV_TOKEN }}
        #name: ${{ matrix.name }}
